import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';

import { useObservations } from '@/context/observations';
import { getTargetById } from '@/data/targets';
import { formatDate } from '@/lib/format';
import type { Observation } from '@/lib/observations';

export default function JournalScreen() {
  const { observations, deleteObservation } = useObservations();
  const remove = (observation: Observation) => Alert.alert('Supprimer l’observation ?', 'Cette action ne peut pas être annulée.', [{ text: 'Annuler', style: 'cancel' }, { text: 'Supprimer', style: 'destructive', onPress: () => deleteObservation(observation.id) }]);
  return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>PLATED</Text><Text style={styles.title}>Journal</Text><Text style={styles.subtitle}>{observations.length ? `${observations.length} observation${observations.length > 1 ? 's' : ''} enregistrée${observations.length > 1 ? 's' : ''}` : 'Toutes vos plaques croisées apparaîtront ici.'}</Text>{observations.length === 0 ? <View style={styles.empty}><MaterialIcons name="history" size={42} color="#91a0a8" /><Text style={styles.emptyTitle}>La route est encore à écrire</Text><Text style={styles.emptyText}>Ajoute une plaque depuis Collection pour démarrer le journal.</Text></View> : observations.map((observation) => { const target = getTargetById(observation.targetId); if (!target) return null; return <View style={styles.card} key={observation.id}><View style={styles.cardTop}><View style={styles.code}><Text style={styles.codeText}>{target.flag ?? target.code}</Text></View><View style={styles.copy}><Text style={styles.name}>{target.name}</Text><Text style={styles.date}>{formatDate(observation.observedAt)}</Text></View><Pressable hitSlop={10} onPress={() => remove(observation)}><MaterialIcons name="delete-outline" size={23} color="#a05c58" /></Pressable></View></View>; })}</ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#f7f8f7' }, content: { padding: 20, paddingBottom: 110 }, kicker: { color: '#0d6e63', fontSize: 12, fontWeight: '900', letterSpacing: 1.8 }, title: { color: '#15202b', fontSize: 32, fontWeight: '900', marginTop: 2 }, subtitle: { color: '#64717b', fontSize: 15, marginTop: 4, marginBottom: 24 }, card: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e5eaec', borderRadius: 17, padding: 14, marginBottom: 10 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, code: { width: 44, height: 44, borderRadius: 13, backgroundColor: '#eff3f4', alignItems: 'center', justifyContent: 'center' }, codeText: { color: '#22303a', fontWeight: '900', fontSize: 14 }, copy: { flex: 1 }, name: { color: '#16212b', fontSize: 16, fontWeight: '800' }, date: { color: '#74808a', fontSize: 12, marginTop: 3 }, empty: { backgroundColor: '#fff', borderRadius: 20, borderWidth: 1, borderColor: '#e5eaec', padding: 30, alignItems: 'center', gap: 10, marginTop: 14 }, emptyTitle: { color: '#26333d', fontWeight: '800', fontSize: 17 }, emptyText: { color: '#75808a', textAlign: 'center', lineHeight: 20 } });
